const fs = require('fs');

const rawBookmarklet = `javascript:(async()=>{const e="suno-lyrics-tools",t="lrc";function n(e){const t=\`; \${document.cookie}\`.split(\`; \${e}=\`);return t.length>1?t[t.length-1].split(";")[0]:null}function o(e){const t=new Date(0);return t.setMilliseconds(1e3*e),\`\${String(t.getUTCHours()).padStart(2,"0")}:\${String(t.getUTCMinutes()).padStart(2,"0")}:\${String(t.getUTCSeconds()).padStart(2,"0")},\${String(t.getUTCMilliseconds()).padStart(3,"0")}\`}function r(e){const t=new Date(0);return t.setMilliseconds(1e3*e),\`[\${String(t.getUTCMinutes()).padStart(2,"0")}:\${String(t.getUTCSeconds()).padStart(2,"0")}.\${String(Math.floor(t.getUTCMilliseconds()/10)).padStart(2,"0")}]\`}function i(e){return e.map((e,t)=>\`\${t+1}\\n\${o(e.start_s)} --> \${o(e.end_s)}\\n\${String(e.word||"").trim()}\\n\`).join("\\n")}function a(e){return e.map(e=>\`\${r(e.start_s)}\${String(e.word||"").trim()}\`).join("\\n")}function d(e,t=700,n=10){let o=[],i="",a=null,d=null,l=0;return e.forEach(e=>{const s=1e3*Number(e.start_s||0),c=String(e.word||"").replace(/\\[.*?\\]/g,"").trim();if(!c)return void(d=s);const u=null!==d&&s-d>t,m=l>=n;i&&(u||m)&&(o.push(\`\${a} \${i.trim()}\`),i="",l=0),i?(i+=" "+c,l++):(a=r(e.start_s),i=c,l=1),d=s}),i&&o.push(\`\${a} \${i.trim()}\`),o.join("\\n")}function l(e,t){const n=new Blob([e],{type:"text/plain;charset=utf-8"}),o=URL.createObjectURL(n),r=document.createElement("a");r.href=o,r.download=t,r.style.display="none",document.body.appendChild(r),r.click(),setTimeout(()=>{URL.revokeObjectURL(o),r.remove()},500)}async function s(e,t){const n=\`https://studio-api.prod.suno.com/api/gen/\${e}/aligned_lyrics/v2/\`,o=await fetch(n,{method:"GET",headers:t?{Authorization:\`Bearer \${t}\`,"Content-Type":"application/json"}:{},credentials:"include"});if(!o.ok)throw new Error(\`HTTP \${o.status}\`);const r=await o.json();return r?.aligned_words||null}function c(e,t,n){const o=document.createElement("button");return o.textContent=e,o.style.cssText=\`padding:10px 12px;border:none;border-radius:8px;background:\${t};color:#fff;font-weight:600;cursor:pointer;box-shadow:0 4px 12px rgba(0,0,0,.2);\`,o.onclick=n,o}function u(n,o){const r=document.getElementById(e);r&&r.remove();const i=document.createElement("div");i.id=e,i.style.cssText="position:fixed;right:16px;bottom:16px;z-index:999999;display:flex;flex-direction:column;gap:8px;",i.appendChild(c(\`Download \${t.toUpperCase()}\`,"#4b5563",()=>{const e="srt"===t?i2(o):a(o);l(e,\`\${n}.\${t}\`)}));function i2(e){return i(e)}i.appendChild(c("Download Formatted LRC","#2563eb",()=>{const e=d(o);l(e,\`\${n}.formatted.lrc\`)\})),document.body.appendChild(i)}try{const o=location.pathname.split("/").filter(Boolean).pop(),r=n("__session");if(!o)throw new Error("No song id found in URL");const i=await s(o,r);if(!i?.length)throw new Error("No aligned words found");u(o,i)}catch(e){console.error("Bookmarklet failed:",e),alert("Bookmarklet failed: "+e.message)}})();`;

let content = fs.readFileSync('src/components/SunoLyricDownloader.tsx', 'utf-8');

// The BOOKMARKLET is currently declared as: const BOOKMARKLET = "javascript:...";
// Let's replace the whole declaration.
content = content.replace(
  /const BOOKMARKLET = "[^]*?";\n/,
  `const BOOKMARKLET = ${JSON.stringify(rawBookmarklet)};\n`
);

fs.writeFileSync('src/components/SunoLyricDownloader.tsx', content);
