const fs = require('fs');
let content = fs.readFileSync('src/App.tsx', 'utf8');

content = content.replace(/const \[tiktokSearchType, setTiktokSearchType\] = useState<"sound" \| "video" \| "youtube" \| "nhaccuatui" \| "tkaraoke">\("sound"\);/, 'const [tiktokSearchType, setTiktokSearchType] = useState<"sound" | "video" | "youtube" | "nhaccuatui" | "tkaraoke">("youtube");');

// Remove Sound button
content = content.replace(/                    <button\n                      type="button"\n                      onClick=\{\(\) => \{\n                        setTiktokSearchType\("sound"\);\n                        if \(tiktokSearchQuery\.trim\(\)\) \{\n                          handleTiktokSearch\(undefined, false, "sound"\);\n                        \} else \{\n                          setTiktokSearchResults\(\[\]\);\n                          setTiktokSearchError\(""\);\n                        \}\n                      \}\}\n                      className=\{\`text-\[8px\] sm:text-\[9px\] font-black tracking-wider uppercase px-1\.5 py-1\.5 rounded-lg transition-all flex items-center gap-1 flex-1 sm:flex-initial justify-center whitespace-nowrap \$\{\n                        tiktokSearchType === "sound"\n                          \? "bg-amber-400 text-black shadow-md shadow-amber-400\/10"\n                          : "text-white\/40 hover:text-white\/75"\n                      \}\`\}\n                    >\n                      <Music className="w-2\.5 h-2\.5 sm:w-3 sm:h-3" \/>\n                      Sound\n                    <\/button>\n/, '');

// Remove Video button
content = content.replace(/                    <button\n                      type="button"\n                      onClick=\{\(\) => \{\n                        setTiktokSearchType\("video"\);\n                        if \(tiktokSearchQuery\.trim\(\)\) \{\n                          handleTiktokSearch\(undefined, false, "video"\);\n                        \} else \{\n                          setTiktokSearchResults\(\[\]\);\n                          setTiktokSearchError\(""\);\n                        \}\n                      \}\}\n                      className=\{\`text-\[8px\] sm:text-\[9px\] font-black tracking-wider uppercase px-1\.5 py-1\.5 rounded-lg transition-all flex items-center gap-1 flex-1 sm:flex-initial justify-center whitespace-nowrap \$\{\n                        tiktokSearchType === "video"\n                          \? "bg-amber-400 text-black shadow-md shadow-amber-400\/10"\n                          : "text-white\/40 hover:text-white\/75"\n                      \}\`\}\n                    >\n                      <Film className="w-2\.5 h-2\.5 sm:w-3 sm:h-3" \/>\n                      Video\n                    <\/button>\n/, '');

fs.writeFileSync('src/App.tsx', content);
